# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20180124_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=26),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=24),
        ),
    ]
